# Generated by Django 4.2.24 on 2026-07-13 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description détaillée de la mission')),
                ('resultat_attendu', models.TextField(help_text='Objectif attendu')),
                ('criteres_validation', models.TextField(help_text='Critères utilisés par le validateur')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='challenges/defis/couvertures/')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('apprenti', 'Apprenti Ambassadeur'), ('actif', 'Ambassadeur actif'), ('leader', 'Leader communautaire')], default='debutant', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('duree_estimee', models.CharField(help_text='Ex. : 30 minutes, 1 semaine', max_length=100)),
                ('points_recompense', models.PositiveIntegerField(default=10)),
                ('nombre_photos_min', models.PositiveSmallIntegerField(default=1)),
                ('nombre_photos_max', models.PositiveSmallIntegerField(default=5)),
                ('video_obligatoire', models.BooleanField(default=False)),
                ('est_obligatoire', models.BooleanField(default=True, help_text='Un défi obligatoire doit être validé pour débloquer le module suivant.')),
                ('est_actif', models.BooleanField(default=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_ouvert', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, help_text='Module dont le quiz débloque ce défi. Laisser vide pour un défi libre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defis', to='formation.module')),
            ],
            options={
                'verbose_name': 'Défi',
                'verbose_name_plural': 'Défis',
                'db_table': 'challenges_defi',
                'ordering': ['niveau', 'ordre', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SoumissionActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport', models.TextField(help_text="Court rapport rédigé par l'ambassadeur")),
                ('date_activite', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('nombre_personnes_sensibilisees', models.PositiveIntegerField(default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='challenges/soumissions/videos/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='challenges.defi')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_activite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Soumission d'activité",
                'verbose_name_plural': "Soumissions d'activité",
                'db_table': 'challenges_soumission_activite',
                'ordering': ['-soumis_le'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('acceptee', 'Acceptée'), ('refusee', 'Refusée')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('points_attribues', models.PositiveIntegerField(default=0)),
                ('points_appliques', models.BooleanField(default=False, help_text="Garantit que les points ne sont ajoutés qu'une seule fois.")),
                ('valide_le', models.DateTimeField(auto_now_add=True)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='challenges.soumissionactivite')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
                'db_table': 'challenges_validation',
            },
        ),
        migrations.CreateModel(
            name='PhotoSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='challenges/soumissions/photos/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('ajoutee_le', models.DateTimeField(auto_now_add=True)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='challenges.soumissionactivite')),
            ],
            options={
                'verbose_name': 'Photo de soumission',
                'verbose_name_plural': 'Photos de soumission',
                'db_table': 'challenges_photo_soumission',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DefiUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('verrouille', 'Verrouillé'), ('disponible', 'Disponible'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='verrouille', max_length=20)),
                ('debloque_le', models.DateTimeField(blank=True, null=True)),
                ('commence_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis_utilisateur', to='challenges.defi')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi utilisateur',
                'verbose_name_plural': 'Défis utilisateur',
                'db_table': 'challenges_defi_utilisateur',
            },
        ),
        migrations.AddConstraint(
            model_name='soumissionactivite',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'en_attente')), fields=('utilisateur', 'defi'), name='challenges_unique_soumission_en_attente'),
        ),
        migrations.AddConstraint(
            model_name='soumissionactivite',
            constraint=models.CheckConstraint(check=models.Q(('nombre_personnes_sensibilisees__gte', 0)), name='challenges_personnes_sensibilisees_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='defiutilisateur',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'defi'), name='challenges_unique_defi_utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='defi',
            constraint=models.CheckConstraint(check=models.Q(('points_recompense__gte', 0)), name='challenges_defi_points_non_negatifs'),
        ),
        migrations.AddConstraint(
            model_name='defi',
            constraint=models.CheckConstraint(check=models.Q(('nombre_photos_max__gte', models.F('nombre_photos_min'))), name='challenges_defi_photos_max_gte_min'),
        ),
    ]
