# Generated by Django 4.2.24 on 2026-07-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_progressionmodule_est_termine'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defi',
            name='est_obligatoire',
            field=models.BooleanField(default=True, help_text='Indique que ce défi compte dans la progression obligatoire de l’utilisateur.'),
        ),
        migrations.AlterField(
            model_name='defi',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module auquel le défi est rattaché. Le quiz ne conditionne pas son accès.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defis', to='formation.module'),
        ),
    ]
