from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[('accounts_user','0001_initial')]
    operations=[
      migrations.CreateModel(name='Annonce',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('titre',models.CharField(max_length=200)),('contenu',models.TextField()),('portee',models.CharField(choices=[('tous','Tous les ambassadeurs'),('region','Une région spécifique'),('niveau','Un niveau spécifique')],default='tous',max_length=20)),('region_ciblee',models.CharField(blank=True,max_length=150,null=True)),('niveau_cible',models.CharField(blank=True,max_length=30,null=True)),('est_active',models.BooleanField(default=True)),('publiee_le',models.DateTimeField(auto_now_add=True)),('expire_le',models.DateTimeField(blank=True,null=True)),('auteur',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='annonces_creees',to='accounts_user.User'))],options={'db_table':'notifications_annonce','ordering':['-publiee_le']}),
      migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('type',models.CharField(default='autre',max_length=30)),('titre',models.CharField(max_length=200)),('message',models.TextField()),('lien',models.CharField(blank=True,max_length=255,null=True)),('est_lue',models.BooleanField(default=False)),('lue_le',models.DateTimeField(blank=True,null=True)),('cree_le',models.DateTimeField(auto_now_add=True)),('destinataire',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notifications',to='accounts_user.User'))],options={'db_table':'notifications_notification','ordering':['-cree_le']}),
      migrations.CreateModel(name='LectureAnnonce',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('lue_le',models.DateTimeField(auto_now_add=True)),('annonce',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='lectures',to='notifications.annonce')),('utilisateur',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='annonces_lues',to='accounts_user.User'))],options={'db_table':'notifications_lecture_annonce','unique_together':{('utilisateur','annonce')}}),
    ]
