# Generated by Django 4.2.24 on 2026-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-publiee_le'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='lectureannonce',
            options={'verbose_name': "Lecture d'annonce", 'verbose_name_plural': "Lectures d'annonce"},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, help_text='Lien interne vers la ressource concernée (ex: /defis/12/)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nouveau_module', 'Nouveau module disponible'), ('quiz_debloque', 'Quiz débloqué'), ('defi_debloque', 'Défi débloqué'), ('soumission_validee', 'Soumission validée'), ('soumission_refusee', 'Soumission refusée'), ('badge_obtenu', 'Badge obtenu'), ('certificat_delivre', 'Certificat délivré'), ('nouveau_commentaire', 'Nouveau commentaire'), ('nouvelle_mention_jaime', "Nouvelle mention j'aime"), ('niveau_atteint', 'Nouveau niveau atteint'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
    ]
