# Generated by Django 4.2.24 on 2026-07-14 11:22

import apps.accounts.user.managers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ambassador', 'Ambassadeur'), ('validator', 'Validateur'), ('moderator', 'Modérateur')], default='ambassador', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_activation_nonce', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Nonce renouvelé à chaque renvoi et après activation afin d'invalider les anciens liens.")),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_user',
            },
            managers=[
                ('objects', apps.accounts.user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOutstandingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('blacklisted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_tokens', to='accounts_user.user')),
            ],
            options={
                'db_table': 'account_user_outstanding_token',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('scout_type', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('sampana', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('fivondronana', models.CharField(blank=True, max_length=150, null=True)),
                ('faritra', models.CharField(blank=True, max_length=150, null=True)),
                ('diosezy', models.CharField(blank=True, max_length=150, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('apprentice', 'Apprenti Ambassadeur'), ('active', 'Ambassadeur actif'), ('leader', 'Leader communautaire')], default='beginner', max_length=30)),
                ('points', models.PositiveIntegerField(default=0)),
                ('progression', models.PositiveIntegerField(default=0)),
                ('current_badge', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts_user.user')),
            ],
            options={
                'db_table': 'account_user_profile',
            },
        ),
    ]
