# Generated by Django 4.2.24 on 2026-07-11 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('explication', models.TextField(blank=True, help_text='Explication affichée après correction (facultatif)', null=True)),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'db_table': 'formation_choix',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField(help_text='Contenu de lecture (2 à 5 minutes)')),
                ('resume', models.TextField(help_text='Résumé des points essentiels')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='formation/modules/couvertures/')),
                ('url_video', models.URLField(blank=True, help_text='Vidéo facultative', null=True)),
                ('niveau', models.CharField(choices=[('débutant', 'Débutant'), ('apprenti', 'Apprenti Ambassadeur'), ('actif', 'Ambassadeur actif'), ('leader', 'Leader communautaire')], default='débutant', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_ouvert', models.BooleanField(default=True, help_text="Ouverture/fermeture manuelle. Prioritaire sur la fenêtre de dates : si False, le module est fermé même si date_debut/date_fin l'autoriseraient.")),
                ('date_debut', models.DateTimeField(blank=True, help_text="Date/heure d'ouverture programmée (facultatif)", null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date/heure de fermeture programmée (facultatif)', null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'formation_module',
                'ordering': ['niveau', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('reponse_courte', 'Réponse courte')], default='choix_unique', max_length=30)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points attribués si la question est correcte')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('reponses_acceptees', models.JSONField(blank=True, default=list, help_text="Liste des réponses valides (texte libre) pour une question de type 'réponse courte'")),
                ('sensible_a_la_casse', models.BooleanField(default=False, help_text='Si True, la casse est prise en compte pour une réponse courte')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'formation_question',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('score_de_reussite', models.PositiveIntegerField(default=50, help_text='Score minimum en % pour valider le quiz')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formation.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'db_table': 'formation_quiz',
            },
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Score obtenu en % (scoring automatique)')),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('est_reussi', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='formation.quiz')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'db_table': 'formation_tentative_quiz',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.CharField(blank=True, max_length=500, null=True)),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('choix_selectionnes', models.ManyToManyField(blank=True, related_name='+', to='formation.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='formation.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='formation.tentativequiz')),
            ],
            options={
                'verbose_name': 'Réponse de quiz',
                'verbose_name_plural': 'Réponses de quiz',
                'db_table': 'formation_reponse_quiz',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formation.quiz'),
        ),
        migrations.CreateModel(
            name='IllustrationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='formation/modules/illustrations/')),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='formation.module')),
            ],
            options={
                'verbose_name': 'Illustration de module',
                'verbose_name_plural': 'Illustrations de module',
                'db_table': 'formation_illustration_module',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='choix',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='formation.question'),
        ),
        migrations.CreateModel(
            name='ProgressionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_lu', models.BooleanField(default=False)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('est_termine', models.BooleanField(default=False, help_text='Terminé = module lu ET quiz réussi')),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formation.module')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_module', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression de module',
                'verbose_name_plural': 'Progressions de module',
                'db_table': 'formation_progression_module',
                'unique_together': {('utilisateur', 'module')},
            },
        ),
    ]
