# Generated by Django 4.2.24 on 2026-07-13 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('explication', models.TextField(blank=True, help_text='Explication affichée après correction (facultatif)', null=True)),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'db_table': 'formation_choix',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField(help_text='Contenu de lecture (2 à 5 minutes)')),
                ('resume', models.TextField(help_text='Résumé des points essentiels')),
                ('image_couverture', models.FileField(blank=True, help_text='Image de couverture téléversée (facultative)', null=True, upload_to='formation/modules/couvertures/')),
                ('video', models.FileField(blank=True, help_text='Fichier vidéo téléversé (facultatif)', null=True, upload_to='formation/modules/videos/')),
                ('niveau', models.CharField(choices=[('débutant', 'Débutant'), ('apprenti', 'Apprenti Ambassadeur'), ('actif', 'Ambassadeur actif'), ('leader', 'Leader communautaire')], default='débutant', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_ouvert', models.BooleanField(default=True, help_text="Ouverture/fermeture manuelle. Prioritaire sur la fenêtre de dates : si False, le module est fermé même si date_debut/date_fin l'autoriseraient.")),
                ('date_debut', models.DateTimeField(blank=True, help_text="Date/heure d'ouverture programmée (facultatif)", null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date/heure de fermeture programmée (facultatif)', null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'formation_module',
                'ordering': ['niveau', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('texte', models.CharField(max_length=500)),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('reponse_courte', 'Réponse courte')], default='choix_unique', max_length=30)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points attribués si la question est correcte', validators=[django.core.validators.MinValueValidator(1)])),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Ordre dans la banque de questions')),
                ('explication', models.TextField(blank=True, help_text="Explication générale retournée lors d'une correction automatique", null=True)),
                ('reponses_acceptees', models.JSONField(blank=True, default=list, help_text='Réponses valides pour une question de type réponse_courte')),
                ('sensible_a_la_casse', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'formation_question',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tirages', to='formation.question')),
            ],
            options={
                'verbose_name': 'Question tirée',
                'verbose_name_plural': 'Questions tirées',
                'db_table': 'formation_question_tentative',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('score_de_reussite', models.PositiveIntegerField(default=50, help_text='Score minimum en % pour valider le quiz', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nombre_questions', models.PositiveIntegerField(default=5, help_text='Nombre de questions tirées aléatoirement dans la banque pour une tentative', validators=[django.core.validators.MinValueValidator(1)])),
                ('correction_automatique', models.BooleanField(default=True, help_text="Si activée, l'API indique immédiatement si une réponse est correcte et, en cas d'erreur, retourne la correction et l'explication disponible.")),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formation.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'db_table': 'formation_quiz',
            },
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumise', 'Soumise')], default='en_cours', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, help_text='Score obtenu en % (scoring automatique)')),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('est_reussi', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('soumise_le', models.DateTimeField(blank=True, null=True)),
                ('questions_tirees', models.ManyToManyField(related_name='tentatives_tirees', through='formation.QuestionTentative', to='formation.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='formation.quiz')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to='accounts_user.User')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'db_table': 'formation_tentative_quiz',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reponse_texte', models.CharField(blank=True, max_length=500, null=True)),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('enregistree_le', models.DateTimeField(auto_now_add=True)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('choix_selectionnes', models.ManyToManyField(blank=True, related_name='+', to='formation.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reponses', to='formation.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='formation.tentativequiz')),
            ],
            options={
                'verbose_name': 'Réponse de quiz',
                'verbose_name_plural': 'Réponses de quiz',
                'db_table': 'formation_reponse_quiz',
            },
        ),
        migrations.AddField(
            model_name='questiontentative',
            name='tentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_selectionnees', to='formation.tentativequiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formation.quiz'),
        ),
        migrations.CreateModel(
            name='ProgressionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_lu', models.BooleanField(default=False)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('est_termine', models.BooleanField(default=False, help_text='Terminé = module lu ET quiz réussi')),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formation.module')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_module', to='accounts_user.User')),
            ],
            options={
                'verbose_name': 'Progression de module',
                'verbose_name_plural': 'Progressions de module',
                'db_table': 'formation_progression_module',
            },
        ),
        migrations.CreateModel(
            name='IllustrationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.FileField(help_text="Fichier d'illustration téléversé", upload_to='formation/modules/illustrations/')),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='formation.module')),
            ],
            options={
                'verbose_name': 'Illustration de module',
                'verbose_name_plural': 'Illustrations de module',
                'db_table': 'formation_illustration_module',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='choix',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='formation.question'),
        ),
        migrations.AddConstraint(
            model_name='tentativequiz',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'en_cours')), fields=('utilisateur', 'quiz'), name='unique_tentative_quiz_en_cours'),
        ),
        migrations.AddConstraint(
            model_name='reponsequiz',
            constraint=models.UniqueConstraint(fields=('tentative', 'question'), name='unique_reponse_question_tentative'),
        ),
        migrations.AddConstraint(
            model_name='questiontentative',
            constraint=models.UniqueConstraint(fields=('tentative', 'question'), name='unique_question_par_tentative'),
        ),
        migrations.AddConstraint(
            model_name='questiontentative',
            constraint=models.UniqueConstraint(fields=('tentative', 'ordre'), name='unique_ordre_par_tentative'),
        ),
        migrations.AddConstraint(
            model_name='progressionmodule',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'module'), name='unique_progression_utilisateur_module'),
        ),
    ]
