# Generated by Django 4.2.24 on 2026-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressionmodule',
            name='est_termine',
            field=models.BooleanField(default=False, help_text='Terminé = lecture + quiz réussi + au moins deux défis validés'),
        ),
    ]
