from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[('accounts_user','0001_initial'),('formation','0001_initial')]
    operations=[
      migrations.CreateModel(name='Badge',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nom',models.CharField(max_length=150,unique=True)),('description',models.TextField()),('icone',models.ImageField(blank=True,null=True,upload_to='recompenses/badges/')),('cree_le',models.DateTimeField(auto_now_add=True))],options={'db_table':'recompenses_badge'}),
      migrations.CreateModel(name='ConfigurationNiveau',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('modules_pour_apprenti',models.PositiveIntegerField(default=2)),('modules_pour_actif',models.PositiveIntegerField(default=5)),('modules_pour_leader',models.PositiveIntegerField(default=8)),('modifie_le',models.DateTimeField(auto_now=True))],options={'db_table':'recompenses_configuration_niveau'}),
      migrations.CreateModel(name='Certificat',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('titre',models.CharField(max_length=200)),('niveau',models.CharField(max_length=30)),('fichier',models.FileField(blank=True,null=True,upload_to='recompenses/certificats/')),('delivre_le',models.DateTimeField(auto_now_add=True)),('utilisateur',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='certificats',to='accounts_user.User'))],options={'db_table':'recompenses_certificat','constraints':[models.UniqueConstraint(fields=('utilisateur','niveau'),name='unique_certificat_niveau_utilisateur')]}),
      migrations.CreateModel(name='BadgeUtilisateur',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('obtenu_le',models.DateTimeField(auto_now_add=True)),('badge',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='attributions',to='recompenses.badge')),('module',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='badges_attribues',to='formation.module')),('utilisateur',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='badges',to='accounts_user.User'))],options={'db_table':'recompenses_badge_utilisateur','constraints':[models.UniqueConstraint(fields=('utilisateur','module'),name='unique_badge_par_module_utilisateur')]}),
    ]
