# Generated by Django 4.2.24 on 2026-07-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recompenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationniveau',
            options={'verbose_name': 'Configuration des niveaux'},
        ),
    ]
